<?php
namespace app\modules\sizes\api;

use Yii;
use yii\data\ActiveDataProvider;
use yii\easyii\models\Tag;
use yii\easyii\widgets\Fancybox;
use yii\widgets\LinkPager;

use app\modules\sizes\models\Sizes as SizesModel;

/**
 * Sizes module API
 * @package app\modules\sizes\api
 *
 * @method static SizesObject get(mixed $id_slug) Get sizes object by id or slug
 * @method static array items(array $options = []) Get list of sizes as SizesObject objects
 * @method static mixed last(int $limit = 1) Get last sizes
 * @method static void plugin() Applies FancyBox widget on photos called by box() function
 * @method static string pages() returns pagination html generated by yii\widgets\LinkPager widget.
 * @method static \stdClass pagination() returns yii\data\Pagination object.
 */

class Sizes extends \yii\easyii\components\API
{
    private $_adp;
    private $_last;
    private $_items;
    private $_item = [];

    public function api_items($options = [])
    {
        if(!$this->_items){
            $this->_items = []; 
          //  $with = ['seo']; 
            $query = SizesModel::find()->status(SizesModel::STATUS_ON);
            $query->sortDate();
          
            $this->_adp = new ActiveDataProvider([
                'query' => $query,
                'pagination' =>   []
            ]); 
            foreach($this->_adp->models as $model){
                $this->_items[] = new SizesObject($model);
            }
        }
        return $this->_items;
    }

    public function api_getbyid($id)
    { 
        return SizesModel::findOne($id);
    }
    
    public function api_get($id_slug)
    {
        if(!isset($this->_item[$id_slug])) {
            $this->_item[$id_slug] = $this->findSizes($id_slug);
        }
        return $this->_item[$id_slug];
    }
    
        public function api_all()
    {
       return SizesModel::find()->asArray()->all();
    }
    
    
    
    
    
    

    public function api_last($limit = 1)
    {
        if($limit === 1 && $this->_last){
            return $this->_last;
        }

        $with = ['seo'];
        if(Yii::$app->getModule('admin')->activeModules['sizes']->settings['enableTags']){
            $with[] = 'tags';
        }

        $result = [];
        foreach(SizesModel::find()->with($with)->status(SizesModel::STATUS_ON)->sortDate()->limit($limit)->all() as $item){
            $result[] = new SizesObject($item);
        }

        if($limit > 1){
            return $result;
        } else {
            $this->_last = count($result) ? $result[0] : null;
            return $this->_last;
        }
    }

    public function api_plugin($options = [])
    {
        Fancybox::widget([
            'selector' => '.easyii-box',
            'options' => $options
        ]);
    }

    public function api_pagination()
    {
        return $this->_adp ? $this->_adp->pagination : null;
    }

    public function api_pages()
    {
        return $this->_adp ? LinkPager::widget(['pagination' => $this->_adp->pagination]) : '';
    }

    private function findSizes($id_slug)
    {
        $sizes = SizesModel::find()->where(['slug=:id_slug'], [':id_slug' => $id_slug])->status(SizesModel::STATUS_ON)->one();
        if($sizes) {
            $sizes->updateCounters(['views' => 1]);
            return new SizesObject($sizes);
        } else {
            return null;
        }
    }
}